config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  get '/react(*path)', to: 'application_react#react', as: 'react'

  namespace :api do
    namespace :v1 do
      resources :shareholders, only: [:index, :show], format: 'json'
      resources :companies, only: [:index, :show], format: 'json'

      get 'shareholders/:id/companies', to: 'shareholders#show_shareholder_companies', format: 'json'
      get 'shareholders/:id/shares', to: 'shareholders#show_shareholder_shares', format: 'json'
    end
  end

  # Defines the root path route ("/")
  root 'companies#index'

  post '/companies/update_companies_list', to: 'companies#update_companies_list'
  post '/companies/update_companies_details', to: 'companies#update_companies_details'
  post '/companies/:id/update_shareholders', to: 'companies#update_company_shareholders',
    as: 'companies_update_company_shareholders'
  post '/companies/update_shareholders', to: 'companies#update_selected_companies_shareholders',
    as: 'companies_update_selected_companies_shareholders'
  post '/companies/:id/update_profile', to: 'companies#update_company_profile',
    as: 'companies_update_company_profile'
  post '/companies/update_profiles', to: 'companies#update_selected_companies_profiles',
    as: 'companies_update_selected_companies_profiles'

  get '/legal_reservations', to: 'static_pages#legal_reservations'

  resources :companies, only: [:index, :show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_many :shares, dependent: :destroy
  has_many :shareholders, through: :shares
end

app/models/share.rb
# frozen_string_literal: true

class Share < ApplicationRecord
  belongs_to :shareholder
  belongs_to :company
end

app/models/shareholder.rb
# frozen_string_literal: true

class Shareholder < ApplicationRecord
  has_many :shares, dependent: :destroy
  has_many :companies, through: :shares
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable, :recoverable,
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  enum role: { role_standard: 0, role_admin: 1 }
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :role_user
  end
end

app/controllers/api/v1/companies_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CompaniesController < ApplicationController
      def index
        respond_to do |format|
          if selector_params_valid?
            @companies = CompaniesSelector.call(params.permit(:query, :stock, :condition))
            format.json { render json: @companies }
          else
            format.json { render json: { error: 'Bad request.' }, status: :unprocessable_entity }
          end
        end
      end

      def show
        company = Company.find(params.require(:id))
        @company = JSON.parse(CompanyPresenter.new(company).to_json)['company']

        respond_to do |format|
          format.json { render json: @company }
        end
      end

      private

      def selector_params_valid?
        Companies::SelectorParamsValidator.new(params.permit(:query, :stock, :condition)).valid?
      end
    end
  end
end

app/controllers/api/v1/shareholders_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ShareholdersController < ApplicationController
      def index
        @shareholders = Shareholder.all

        respond_to do |format|
          format.json { render json: @shareholders }
        end
      end

      def show
        @shareholder = Shareholder.find(params.require(:id))

        respond_to do |format|
          format.json { render json: @shareholder }
        end
      end

      def show_shareholder_companies
        shareholder = Shareholder.find(params.require(:id))

        respond_to do |format|
          format.json { render json: shareholder.companies }
        end
      end

      def show_shareholder_shares
        shareholder = Shareholder.find(params.require(:id))

        respond_to do |format|
          format.json { render json: shareholder.shares }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :info, :error
end

app/controllers/application_react_controller.rb
# frozen_string_literal: true

class ApplicationReactController < ApplicationController
  add_flash_types :info, :error

  def react
    render 'react_app'
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  def index
    if selector_params_valid?
      @companies = CompaniesSelector.call(params.permit(:query, :stock, :condition))
      render 'index'
    else
      render file: Rails.public_path.join('400.html'), layout: false
    end
  end

  def show
    company = Company.find(params.require(:id))
    @company = CompanyPresenter.new(company)
  end

  def show_company_shareholders
    @company = Company.find(params[:id])
  end

  def update_companies_list
    CompaniesListUpdator.call
    redirect_to companies_url, notice: t('companies.update_companies_list.success')
  end

  def update_companies_details
    CompaniesDetailsUpdator.call
    redirect_to companies_url, notice: t('companies.update_companies_details.success')
  end

  def update_company_profile
    CompanyProfileUpdator.call(params.require(:id))
    redirect_to company_url(params.require(:id)), notice: t('companies.update_company_profile.success')
  end

  def update_selected_companies_profiles
    if selector_params_valid?
      companies = CompaniesSelector.call(params.permit(:query, :stock, :condition))
      CompaniesProfilesUpdator.call(companies)
      redirect_to companies_url(params[:stock]), notice: t('companies.update_selected_companies_profiles.success')
    else
      render file: Rails.public_path.join('400.html'), layout: false
    end
  end

  def update_selected_companies_shareholders
    if selector_params_valid?
      companies = CompaniesSelector.call(params.permit(:query, :stock, :condition))
      CompaniesShareholdersUpdator.call(companies)
      redirect_to companies_url(params[:stock]), notice: t('companies.update_selected_companies_shareholders.success')
    else
      render_bad_request_error
    end
  end

  def update_company_shareholders
    CompanyShareholdersUpdator.call(params.require(:id))
    redirect_to company_url(params.require(:id)), notice: t('companies.update_company_shareholders.success')
  end

  private

  def selector_params_valid?
    Companies::SelectorParamsValidator.new(params.permit(:query, :stock, :condition)).valid?
  end

  def render_bad_request_error
    render file: Rails.public_path.join('400.html'), layout: false
  end
end

app/controllers/shareholders_controller.rb
# frozen_string_literal: true

class ShareholdersController < ApplicationController
  def index; end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application_react/react_app.html.erb
<div id="root"></div>

app/views/companies/_banner.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
   <div class="container-fluid">

      <a class="navbar-brand" href="<%= root_path %>">JSCLook</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
         aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item active">
               <a class="nav-link" href="<%= root_path %>">Home </a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="https://www.gpw.pl/">GPW</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="https://newconnect.pl/">NewConnect</a>
            </li>
         </ul>

         <!--
         <div  class="mx-auto">
            <form class="d-flex">
               <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
               <button class="btn btn-outline-secondary btn-sm" type="submit" role="button">Search</button>
            </form>
         </div> -->

         <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <ul class="navbar-nav">
               <li class="nav-item">
                  <button role="button" class="btn btn-outline-success">Login</button>
               </li>
            </ul>
         </div>
      </div>
   </div>
</nav>

app/views/companies/_companies.html.erb
<table class="table table-striped table-sm ">
  <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Joint Stock Company</th>
        <th scope="col">Symbol/ISIN</th>
        <th scope="col">Stock</th>
        <th scope="col">Shares amount</th>
      </tr>
    </thead>
    <tbody>
      <% companies.each.with_index(1) do |company, index| %>
        <tr>
          <td class="text-dark" ><%= index %></td>
          <td><%= link_to company.name, company_path(company.id), class: "nav-link text-dark p-0" %></td>
          <td class="text-muted" ><%= company.isin %></td>
          <td class="text-muted" ><%= company.stock %></td>
          <td class="text-muted" ><%= company.shares_amount %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/companies/_company.html.erb
<div class="container">
  <div class="container">
    <h4><%= @company.name %></h4>
    <p class='small text-muted'><%= @company.belong_to %></p>
  </div>
  <div class="col m-2">
    <div class="row">
      <div class="col">
        <p>P/BV</p>
        <p>P/E</p>
        <p>Capitalization</p>
        <p>Book value</p>
        <p><%= link_to 'Shares', companies_show_company_shareholders_path(@company.id), class: "nav-link text-primary p-0" %></p>
        <p>Stock</p><br />
      </div>
      <div class="col">
        <p><%= @company.pbv %></p>
        <p><%= @company.pe %></p>
        <p><%= @company.price %></p>
        <p><%= @company.book_value %></p>
        <p><%= @company.shares_amount %></p>
        <p><%= @company.stock %></p><br />
      </div>

      <dic class="row">
      <div class="col">
        <p>Full name</p><br />
        <p>Sector</p><br />
        <p>www</p><br />
      </div>
      <div class="col">
        <p><%= @company.full_name %></p><br />
        <p><%= @company.sector %></p><br />
        <p><%= @company.www %></p><br />
      </div>
    </div>
  </div>
</div>

app/views/companies/_company_shareholders.html.erb
<p>This part is under development</p>
<p>You will see shareholders soon</p>

app/views/companies/_confirm_update_db.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#updateCompaniesList">
  UPDATE&nbsp;companies&nbsp;list
</button>

<!-- Modal -->
<div class="modal fade" id="updateCompaniesList" tabindex="-1" role="dialog"
 aria-labelledby="updateCompaniesList" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateTitle">Confirm to update comanies database</h5>
        <button class="btn-close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        By confirm you will download actual companies list <br />
        and upadte companies databese.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Dismiss</button>
        <%= link_to 'Update', companies_update_db_path, class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_fetch_companies_details.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#fetchCompaniesDetails">
  UPDATE&nbsp;companies&nbsp;details
</button>

<!-- Modal -->
<div class="modal fade" id="fetchCompaniesDetails" tabindex="-1" role="dialog"
 aria-labelledby="fetchCompaniesDetails" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fetchTitle">Confirm to update comanies datails</h5>
        <button class="btn-close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        By confirm you will download actual companies details
        and update companies database.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Dismiss</button>
        <%= button_to 'Update', companies_update_companies_details_path, method: :post, class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_fetch_companies_list.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#fetchCompaniesList">
  UPDATE&nbsp;companies&nbsp;list
</button>

<!-- Modal -->
<div class="modal fade" id="fetchCompaniesList" tabindex="-1" role="dialog"
 aria-labelledby="fetchCompaniesList" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fetchTitle">Confirm to update comanies database</h5>
        <button class="btn-close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        By confirm you will download actual companies list
        and update companies database.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Dismiss</button>
        <%= button_to 'Update', companies_update_companies_list_path, method: :post, class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_fetch_companies_profiles.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#fetchCompaniesProfiles">
  UPDATE&nbsp;companies&nbsp;profiles
</button>

<!-- Modal -->
<div class="modal fade" id="fetchCompaniesProfiles" tabindex="-1" role="dialog"
 aria-labelledby="fetchCompaniesProfiles" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fetchTitle">Select and confirm to update selected companies profiles</h5>
        <button class="btn-close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        By confirm you will download actual selected companies profiles
        and update companies database.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Dismiss</button>
        <%= form_with url: companies_update_selected_companies_profiles_path, method: :post, class: "form-inline d-flex" do |f| %>
          <div class="container-fluid">
            <%= f.select :stock, ["GPW"], selected: "GPW", class: "form-select form-select-sm" %>
          </div>
          <%= f.submit "Update", class: "btn btn-outline-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_fetch_companies_shareholders.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#fetchCompaniesShareholders">
  UPDATE&nbsp;companies&nbsp;shareholders
</button>

<!-- Modal -->
<div class="modal fade" id="fetchCompaniesShareholders" tabindex="-1" role="dialog"
 aria-labelledby="fetchCompaniesShareholders" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fetchTitle">Select and confirm to update selected companies shareholders</h5>
        <button class="btn-close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        By confirm you will download actual selected companies shareholders
        and update companies shareholders database.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Dismiss</button>
        <%= form_with url: companies_update_selected_companies_shareholders_path, method: :post, class: "form-inline d-flex" do |f| %>
          <div class="container-fluid">
            <%= f.select :stock, ["GPW", "NC"], selected: "GPW", class: "form-select form-select-sm" %>
          </div>
          <%= f.submit "Update", class: "btn btn-outline-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_fetch_company_shareholders.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#fetchCompanyShareholders">
  UPDATE&nbsp;company&nbsp;shareholders
</button>

<!-- Modal -->
<div class="modal fade" id="fetchCompanyShareholders" tabindex="-1" role="dialog"
 aria-labelledby="fetchCompanyShareholders" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fetchTitle">Confirm to update company shareholders</h5>
        <button class="btn-close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        By confirm you will download actual company shareholders
        and update company shareholders database.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Dismiss</button>
        <%= button_to 'Update', companies_update_company_shareholders_path(@company.id), method: :post, class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/companies/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
   <div class="container-fluid">

      <a class="navbar-brand" href="<%= root_path %>">JSCLook</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
         aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item active">
               <a class="nav-link" href="<%= root_path %>">Home </a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="https://www.gpw.pl/">GPW</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="https://newconnect.pl/">NewConnect</a>
            </li>
         </ul>

         <!--
         <div  class="mx-auto">
            <form class="d-flex">
               <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
               <button class="btn btn-outline-secondary btn-sm" type="submit" role="button">Search</button>
            </form>
         </div> -->

         <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <ul class="navbar-nav">
               <li class="nav-item">
                  <button role="button" class="btn btn-outline-success">Login</button>
               </li>
            </ul>
         </div>
      </div>
   </div>
</nav>

app/views/companies/index.html.erb
<nav class="breadcrumb">
  <%= link_to 'Home', root_path, class: "breadcrumb-item small text-decoration-none" %>
  <% if params[:query] %>
    <%= link_to 'Stock', companies_path, class: "breadcrumb-item small text-decoration-none" %>
    <span class="breadcrumb-item active small">Search result</span>
  <% elsif params[:stock] %>
    <span class="breadcrumb-item active small "><%= params[:stock] %> Stock</span>
  <% else %>
    <span class="breadcrumb-item active small ">Stock</span>
  <% end %>
</nav>

<noscript>
  <div class="alert alert-warning d-flex align-items-center mt-2" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
  <div>
  <div class="notice">You don't have javascript enabled. Please follow this link for assistance in turning it on.
    <%= link_to "Turn on javascript", "http://www.enable-javascript.com" %>
  </div>
</noscript>

<%= render 'companies', companies: @companies %>

app/views/companies/show.html.erb
<nav class="breadcrumb">
  <%= link_to 'Home', root_path, class: "breadcrumb-item small text-decoration-none" %>
  <%= link_to 'Stock', companies_path, class: "breadcrumb-item small text-decoration-none" %>
  <span class="breadcrumb-item active small"><%= @company.name %></span>
</nav>

<div class="container">
  <div class="container">
    <h4><%= @company.name %></h4>
    <p class='small text-muted'><%= @company.belong_to %></p>
  </div>
  <hr />
  <div class="col m-2">
    <div class="row">
      <div class="col">
        <p>P/BV</p>
        <p>P/E</p>
        <p>Capitalization</p>
        <p>Book value (PLN)</p>
        <p>Shares amount</p>
        <p>Stock</p><br />
      </div>
      <div class="col">
        <p><%= @company.pbv %></p>
        <p><%= @company.pe %></p>
        <p><%= @company.price %>  million</p>
        <p><%= @company.book_value %>  million</p>
        <p><%= @company.shares_amount %></p>
        <p><%= @company.stock %></p><br />
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p>Full name</p><br />
        <p>Sector</p><br />
        <p>www</p><br />
      </div>
      <div class="col">
        <p><%= @company.full_name %></p><br />
        <p><%= @company.sector %></p><br />
        <p><%= @company.www %></p><br />
      </div>
    </div>
  </div>
</div>

app/views/companies/show_company_shareholders.html.erb
<nav class="breadcrumb">
  <%= link_to 'Home', root_path, class: "breadcrumb-item small text-decoration-none" %>
  <%= link_to 'Stock', companies_path, class: "breadcrumb-item small text-decoration-none" %>
  <%= link_to @company.name, company_path(@company.id), class: "breadcrumb-item small text-decoration-none" %></td>
  <span class="breadcrumb-item active small">Shareholders</span>
</nav>

<%= render 'company_shareholders', company: @company %>

app/views/layouts/_admin_panel.html.erb
<div class="mt-2">
  <%= render 'companies/fetch_companies_list' %>
</div>
<div class="mt-2">
  <%= render 'companies/fetch_companies_details' %>
</div>

app/views/layouts/_admin_section.html.erb
<div class="mt-2">
  <%= render 'companies/fetch_companies_list' %>
</div>
<div class="mt-2">
  <%= render 'companies/fetch_companies_details' %>
</div>
<div class="mt-2">
  <%= render 'companies/fetch_companies_profiles' %>
</div>
<div class="mt-2">
  <%= render 'companies/fetch_companies_shareholders' %>
</div>
<% if @company %>
  <div class="mt-2">
    <%= render '/companies/fetch_company_profile' %>
  </div>
  <div class="mt-2">
    <%= render '/companies/fetch_company_shareholders' %>
  </div>
<% end %>

app/views/layouts/_aside.html.erb
<%= form_with url: companies_path, method: :get, class: "form-inline d-flex" do |f| %>
  <%= f.search_field :query, class: "form-control mr-sm-2 d-inline", placeholder: "Search" %>
  <%= f.hidden_field condition: "company_active" %>
  <%= f.submit "Search", class: "btn btn-outline-secondary btn-sm d-inline" %>
<% end %>

app/views/layouts/_footer.html.erb
<ul class="nav justify-content-center flex-nowrap">
  <li class="nav-item">
    <a class="nav-link  href="#">About</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Help</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Contact</a>
  </li>
  <li class="nav-item">
    <%= link_to "Legal\u00a0reservations", legal_reservations_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">&copy;&nbsp;2022</a>
  </li>
</ul>

<ul class="nav justify-content-center flex-nowrap">
  <li class="nav-item">
    <a class="nav-link text-secondary" href="https://www.gpw.pl/">Go to GPW</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-secondary" href="https://newconnect.pl/">Go to NewConnect</a>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">

   <%= link_to 'JSCLook', companies_path(condition: 'company_active'), class: "navbar-brand" %>
   <%= link_to 'JSCLook_React', react_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <%= link_to 'GPW', companies_path(stock: 'GPW', condition: 'company_active'), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'NC', companies_path(stock: 'NC', condition: 'company_active'), class: "nav-link" %>
            </li>
         </ul>

      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= render '/layouts/session' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_right_menu.html.erb
<% if current_user %>
  <% if current_user.role_admin? %>
    <%= render 'layouts/admin_section' %>
  <% end %>
<% end %>

app/views/shareholders/_shareholders.html.erb
<p>This part is under development</p>
<p>You will see shareholders soon</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>